Commissions: ["Commissions", "Commission", "委托", "委託"]
Mailbox: ["Mail", "Mailbox", "信箱", "メール"]
Missions: ["Missions", "Tasks", "任務"]
Gems: ["Gems", "钻石", "ダイヤ"]
Oil: ["Oil", "燃料"]
Coins: ["Coins", "金币", "資金"]
Back: ["Back", "返回", "戻る"]
Claim: ["Claim", "Collect", "收取", "領取", "受取"]
Build: ["Build", "Construct", "建造", "建設"]
Dock: ["Dock", "Fleet", "艦隊", "ドック"]
Academy: ["Academy", "School", "学院", "アカデミー"]
Shop: ["Shop", "Store", "商店", "ショップ"]